"""
Domain Sources — مصادر المجالات المعرفية المدمجة
=================================================
جميع المعرفة مدمجة مباشرة في الكود — لا ملفات منفصلة.
المجالات: الفيزياء، الرياضيات، التاريخ، الأحياء، الحضارات.

كل عنصر:
  concept, text, cluster, importance, certainty, abstraction, year, relations
"""
from __future__ import annotations

from typing import Dict, List, Any


def get_physics_items() -> List[Dict[str, Any]]:
    return [
        {
            "concept": "قانون نيوتن الأول",
            "text": "الجسم الساكن يبقى ساكناً والجسم المتحرك يبقى متحركاً بسرعة ثابتة ما لم تؤثر عليه قوة خارجية.",
            "cluster": "ميكانيكا كلاسيكية", "importance": 0.95, "certainty": 1.0, "abstraction": 0.4,
            "year": 1687,
            "relations": [{"target": "قانون نيوتن الثاني", "type": "precedes", "weight": 0.9},
                          {"target": "القصور الذاتي", "type": "defines", "weight": 0.95}],
        },
        {
            "concept": "قانون نيوتن الثاني",
            "text": "القوة تساوي الكتلة مضروبة في التسارع: F = ma.",
            "cluster": "ميكانيكا كلاسيكية", "importance": 0.98, "certainty": 1.0, "abstraction": 0.3,
            "year": 1687,
            "relations": [{"target": "قانون نيوتن الأول", "type": "follows", "weight": 0.9},
                          {"target": "قانون نيوتن الثالث", "type": "related", "weight": 0.9}],
        },
        {
            "concept": "قانون نيوتن الثالث",
            "text": "لكل فعل ردة فعل مساوية له في المقدار ومعاكسة في الاتجاه.",
            "cluster": "ميكانيكا كلاسيكية", "importance": 0.95, "certainty": 1.0, "abstraction": 0.4,
            "year": 1687,
            "relations": [{"target": "قانون نيوتن الثاني", "type": "follows", "weight": 0.9}],
        },
        {
            "concept": "قانون الجاذبية العامة",
            "text": "قوة الجذب بين جسمين تتناسب طردياً مع حاصل ضرب كتلتيهما وعكسياً مع مربع المسافة بينهما: F = G·m₁·m₂/r².",
            "cluster": "جاذبية", "importance": 0.98, "certainty": 1.0, "abstraction": 0.5,
            "year": 1687,
            "relations": [{"target": "قانون نيوتن الثاني", "type": "derived_from", "weight": 0.8},
                          {"target": "النسبية العامة", "type": "superseded_by", "weight": 0.7}],
        },
        {
            "concept": "النسبية الخاصة",
            "text": "لا شيء يتحرك بسرعة أكبر من الضوء. الكتلة والطاقة مترادفتان: E = mc².",
            "cluster": "نسبية", "importance": 0.99, "certainty": 1.0, "abstraction": 0.7,
            "year": 1905,
            "relations": [{"target": "النسبية العامة", "type": "precedes", "weight": 0.9},
                          {"target": "ثابت سرعة الضوء", "type": "uses", "weight": 0.95}],
        },
        {
            "concept": "النسبية العامة",
            "text": "الجاذبية ليست قوة بل انحناء في نسيج الزمكان تسببه الكتلة والطاقة.",
            "cluster": "نسبية", "importance": 0.99, "certainty": 0.95, "abstraction": 0.85,
            "year": 1915,
            "relations": [{"target": "الثقوب السوداء", "type": "predicts", "weight": 0.9},
                          {"target": "النسبية الخاصة", "type": "extends", "weight": 0.9}],
        },
        {
            "concept": "ميكانيكا الكم",
            "text": "الجسيمات الدقيقة تتصرف كموجات وجسيمات في آنٍ معاً. مبدأ عدم اليقين لهايزنبرغ: لا يمكن قياس الموضع والزخم بدقة في آنٍ واحد.",
            "cluster": "كم", "importance": 0.99, "certainty": 0.95, "abstraction": 0.9,
            "year": 1925,
            "relations": [{"target": "موجة دي برولي", "type": "includes", "weight": 0.85},
                          {"target": "معادلة شرودنغر", "type": "formalized_by", "weight": 0.9}],
        },
        {
            "concept": "معادلة شرودنغر",
            "text": "المعادلة الموجية الأساسية في ميكانيكا الكم: iℏ ∂ψ/∂t = Ĥψ. تصف كيفية تطور الحالة الكمومية عبر الزمن.",
            "cluster": "كم", "importance": 0.95, "certainty": 0.98, "abstraction": 0.85,
            "year": 1926,
            "relations": [{"target": "ميكانيكا الكم", "type": "part_of", "weight": 0.95}],
        },
        {
            "concept": "قوانين الديناميكا الحرارية",
            "text": "الأول: الطاقة لا تُخلق ولا تفنى. الثاني: الإنتروبيا في الأنظمة المعزولة لا تتناقص. الثالث: الإنتروبيا تقترب من الصفر عند الصفر المطلق.",
            "cluster": "ديناميكا حرارية", "importance": 0.97, "certainty": 1.0, "abstraction": 0.6,
            "year": 1850,
            "relations": [{"target": "الإنتروبيا", "type": "defines", "weight": 0.9},
                          {"target": "حفظ الطاقة", "type": "includes", "weight": 0.95}],
        },
        {
            "concept": "الموجة الكهرومغناطيسية",
            "text": "معادلات ماكسويل تصف كيف تولّد الحقول الكهربائية والمغناطيسية المتغيرة موجات تنتشر بسرعة الضوء.",
            "cluster": "كهرومغناطيسية", "importance": 0.97, "certainty": 1.0, "abstraction": 0.65,
            "year": 1865,
            "relations": [{"target": "ثابت سرعة الضوء", "type": "predicts", "weight": 0.9},
                          {"target": "النسبية الخاصة", "type": "inspired", "weight": 0.85}],
        },
        {
            "concept": "الثقوب السوداء",
            "text": "منطقة في الزمكان شديدة الانحناء لدرجة أن لا شيء — ولا حتى الضوء — يستطيع الإفلات منها. حد شوارزشيلد يحدد نقطة اللاعودة.",
            "cluster": "فيزياء فلكية", "importance": 0.9, "certainty": 0.9, "abstraction": 0.7,
            "year": 1916,
            "relations": [{"target": "النسبية العامة", "type": "derived_from", "weight": 0.95},
                          {"target": "إشعاع هوكينغ", "type": "related", "weight": 0.8}],
        },
        {
            "concept": "الفيزياء النووية",
            "text": "دراسة نواة الذرة وقواها. يحتوي النواة على بروتونات ونيوترونات تربطها القوة النووية الشديدة. الانشطار والاندماج يُطلقان طاقة هائلة.",
            "cluster": "فيزياء نووية", "importance": 0.92, "certainty": 0.98, "abstraction": 0.6,
            "year": 1932,
            "relations": [{"target": "ميكانيكا الكم", "type": "uses", "weight": 0.85}],
        },
        {
            "concept": "النموذج القياسي",
            "text": "نظرية شاملة تصف الجسيمات الأولية والقوى الأساسية (إلا الجاذبية). تشمل الكواركات والليبتونات والبوزونات الناقلة للقوى.",
            "cluster": "فيزياء الجسيمات", "importance": 0.96, "certainty": 0.95, "abstraction": 0.9,
            "year": 1970,
            "relations": [{"target": "ميكانيكا الكم", "type": "extends", "weight": 0.9},
                          {"target": "بوزون هيغز", "type": "includes", "weight": 0.9}],
        },
        {
            "concept": "بوزون هيغز",
            "text": "الجسيم المسؤول عن إعطاء الكتلة للجسيمات الأخرى عبر آلية هيغز. اكتُشف تجريبياً عام 2012 في مصادم هادرون الكبير.",
            "cluster": "فيزياء الجسيمات", "importance": 0.9, "certainty": 0.92, "abstraction": 0.85,
            "year": 2012,
            "relations": [{"target": "النموذج القياسي", "type": "part_of", "weight": 0.95}],
        },
        {
            "concept": "ثابت سرعة الضوء",
            "text": "سرعة الضوء في الفراغ: c ≈ 299,792,458 م/ث. ثابت كوني أساسي يربط الزمان والمكان.",
            "cluster": "ثوابت كونية", "importance": 0.95, "certainty": 1.0, "abstraction": 0.3,
            "year": 1676,
            "relations": [{"target": "النسبية الخاصة", "type": "central_to", "weight": 0.98}],
        },
    ]


def get_math_items() -> List[Dict[str, Any]]:
    return [
        {
            "concept": "نظرية فيثاغورس",
            "text": "في المثلث القائم: مربع الوتر يساوي مجموع مربعي الضلعين الآخرين: a² + b² = c².",
            "cluster": "هندسة", "importance": 0.98, "certainty": 1.0, "abstraction": 0.4,
            "year": -530,
            "relations": [{"target": "المثلثات", "type": "foundation_of", "weight": 0.9},
                          {"target": "الهندسة الإقليدية", "type": "part_of", "weight": 0.85}],
        },
        {
            "concept": "حساب التفاضل والتكامل",
            "text": "فرع الرياضيات الذي يدرس معدلات التغير (التفاضل) والتراكم (التكامل). طوّره نيوتن وليبنتز بشكل مستقل.",
            "cluster": "تحليل رياضي", "importance": 0.99, "certainty": 1.0, "abstraction": 0.7,
            "year": 1666,
            "relations": [{"target": "المشتقة", "type": "includes", "weight": 0.95},
                          {"target": "التكامل", "type": "includes", "weight": 0.95},
                          {"target": "نظرية الأساس", "type": "proven_by", "weight": 0.9}],
        },
        {
            "concept": "المشتقة",
            "text": "معدل التغير الفوري لدالة. f'(x) = lim[h→0] (f(x+h) - f(x))/h. تمثل ميل المنحنى عند نقطة.",
            "cluster": "تحليل رياضي", "importance": 0.95, "certainty": 1.0, "abstraction": 0.6,
            "year": 1666,
            "relations": [{"target": "حساب التفاضل والتكامل", "type": "part_of", "weight": 0.95}],
        },
        {
            "concept": "التكامل",
            "text": "عملية إيجاد المساحة تحت المنحنى أو التراكم. عكس التفاضل. ∫f(x)dx.",
            "cluster": "تحليل رياضي", "importance": 0.95, "certainty": 1.0, "abstraction": 0.6,
            "year": 1666,
            "relations": [{"target": "حساب التفاضل والتكامل", "type": "part_of", "weight": 0.95},
                          {"target": "المشتقة", "type": "inverse_of", "weight": 0.98}],
        },
        {
            "concept": "هوية أويلر",
            "text": "e^(iπ) + 1 = 0. تجمع أهم خمسة أعداد رياضية: e، i، π، 1، 0 في معادلة واحدة.",
            "cluster": "تحليل مركب", "importance": 0.97, "certainty": 1.0, "abstraction": 0.8,
            "year": 1748,
            "relations": [{"target": "الأعداد المركبة", "type": "uses", "weight": 0.9},
                          {"target": "صيغة أويلر", "type": "derived_from", "weight": 0.95}],
        },
        {
            "concept": "نظرية الأعداد الأولية",
            "text": "توزيع الأعداد الأولية بين الأعداد الطبيعية. حدسية ريمان تصف هذا التوزيع وتبقى من أعظم المسائل المفتوحة.",
            "cluster": "نظرية الأعداد", "importance": 0.9, "certainty": 0.85, "abstraction": 0.8,
            "year": 1859,
            "relations": [{"target": "الأعداد الأولية", "type": "studies", "weight": 0.95}],
        },
        {
            "concept": "الجبر الخطي",
            "text": "دراسة المتجهات والمصفوفات والتحويلات الخطية. أساس الرياضيات التطبيقية والذكاء الاصطناعي.",
            "cluster": "جبر", "importance": 0.96, "certainty": 1.0, "abstraction": 0.7,
            "year": 1844,
            "relations": [{"target": "المصفوفات", "type": "includes", "weight": 0.95},
                          {"target": "الشبكات العصبية", "type": "foundation_of", "weight": 0.9}],
        },
        {
            "concept": "نظرية فيرما الأخيرة",
            "text": "لا توجد أعداد صحيحة موجبة x, y, z تحقق xⁿ + yⁿ = zⁿ لأي n > 2. أُثبتت من قِبَل واليس عام 1995.",
            "cluster": "نظرية الأعداد", "importance": 0.88, "certainty": 1.0, "abstraction": 0.75,
            "year": 1995,
            "relations": [{"target": "نظرية الأعداد", "type": "part_of", "weight": 0.85}],
        },
        {
            "concept": "الاحتمالات والإحصاء",
            "text": "الاحتمال يقيس إمكانية وقوع حدث. الإحصاء يستنتج خصائص مجتمع من عينة. قانون الأعداد الكبيرة: متوسط العينات يقترب من المتوسط الحقيقي.",
            "cluster": "احتمالات", "importance": 0.95, "certainty": 1.0, "abstraction": 0.6,
            "year": 1654,
            "relations": [{"target": "التوزيع الطبيعي", "type": "includes", "weight": 0.85},
                          {"target": "الشبكات العصبية", "type": "foundation_of", "weight": 0.8}],
        },
        {
            "concept": "الهندسة غير الإقليدية",
            "text": "هندسة تتجاوز بديهيات إقليدس. في الهندسة الكروية المثلثات مجموع زواياها أكبر من 180°. أساس النسبية العامة.",
            "cluster": "هندسة", "importance": 0.88, "certainty": 1.0, "abstraction": 0.8,
            "year": 1830,
            "relations": [{"target": "النسبية العامة", "type": "used_by", "weight": 0.9},
                          {"target": "الهندسة الإقليدية", "type": "extends", "weight": 0.85}],
        },
        {
            "concept": "نظرية المجموعات",
            "text": "الإطار الأساسي للرياضيات الحديثة. المجموعة هي تجميع من العناصر. بديهيات ZFC تؤسس الرياضيات على المجموعات.",
            "cluster": "منطق رياضي", "importance": 0.9, "certainty": 1.0, "abstraction": 0.85,
            "year": 1874,
            "relations": [{"target": "المنطق الرياضي", "type": "related", "weight": 0.85}],
        },
        {
            "concept": "نظرية الرسوم البيانية",
            "text": "دراسة الشبكات: عقد وحواف. تُستخدم في الخوارزميات وشبكات الحاسوب والشبكات الاجتماعية.",
            "cluster": "رياضيات تطبيقية", "importance": 0.88, "certainty": 1.0, "abstraction": 0.6,
            "year": 1736,
            "relations": [{"target": "الخوارزميات", "type": "used_in", "weight": 0.9}],
        },
        {
            "concept": "التحويل الفورييه",
            "text": "يحلّل أي إشارة إلى مجموع من الموجات الجيبية. أساسي في معالجة الإشارات والضغط وتحليل الصوت والصورة.",
            "cluster": "تحليل رياضي", "importance": 0.92, "certainty": 1.0, "abstraction": 0.7,
            "year": 1822,
            "relations": [{"target": "معالجة الإشارات", "type": "used_in", "weight": 0.95}],
        },
        {
            "concept": "الخوارزميات",
            "text": "خطوات محددة ومنتهية لحل مسألة. تُقيَّم بالتعقيد الزمني O(n) والمكاني. أساس علم الحاسوب.",
            "cluster": "رياضيات تطبيقية", "importance": 0.95, "certainty": 1.0, "abstraction": 0.5,
            "year": 825,
            "relations": [{"target": "نظرية الرسوم البيانية", "type": "uses", "weight": 0.85}],
        },
        {
            "concept": "حساب المتغيرات",
            "text": "يبحث عن الدالة التي تُعظّم أو تُصغّر تكاملاً. أساس الفيزياء النظرية والتحكم الأمثل.",
            "cluster": "تحليل رياضي", "importance": 0.85, "certainty": 1.0, "abstraction": 0.8,
            "year": 1696,
            "relations": [{"target": "حساب التفاضل والتكامل", "type": "extends", "weight": 0.9}],
        },
    ]


def get_history_items() -> List[Dict[str, Any]]:
    return [
        {
            "concept": "الثورة الصناعية",
            "text": "تحول جذري في الإنتاج من اليدوي إلى الآلي. بدأت في إنجلترا حوالي 1760 وغيّرت المجتمع الإنساني كلياً.",
            "cluster": "تاريخ حديث", "importance": 0.97, "certainty": 0.95, "abstraction": 0.4,
            "year": 1760,
            "relations": [{"target": "الآلة البخارية", "type": "driven_by", "weight": 0.9},
                          {"target": "الرأسمالية", "type": "accelerated", "weight": 0.85}],
        },
        {
            "concept": "الحرب العالمية الأولى",
            "text": "1914-1918. أشعلها اغتيال فرانز فرديناند. 20 مليون ضحية. أنهت الإمبراطوريات العثمانية والنمساوية والروسية والألمانية.",
            "cluster": "تاريخ معاصر", "importance": 0.96, "certainty": 0.98, "abstraction": 0.3,
            "year": 1914,
            "relations": [{"target": "الحرب العالمية الثانية", "type": "caused", "weight": 0.8},
                          {"target": "معاهدة فرساي", "type": "ended_by", "weight": 0.9}],
        },
        {
            "concept": "الحرب العالمية الثانية",
            "text": "1939-1945. أوسع نزاع في التاريخ. 70-85 مليون ضحية. أسفرت عن قيام الأمم المتحدة والحرب الباردة.",
            "cluster": "تاريخ معاصر", "importance": 0.98, "certainty": 0.98, "abstraction": 0.3,
            "year": 1939,
            "relations": [{"target": "الهولوكوست", "type": "includes", "weight": 0.85},
                          {"target": "الأمم المتحدة", "type": "led_to", "weight": 0.9}],
        },
        {
            "concept": "الثورة الفرنسية",
            "text": "1789-1799. أسقطت الملكية وأعلنت حقوق الإنسان والمواطن. أثّرت على الديمقراطيات الحديثة عالمياً.",
            "cluster": "تاريخ حديث", "importance": 0.95, "certainty": 0.97, "abstraction": 0.4,
            "year": 1789,
            "relations": [{"target": "نابليون بونابرت", "type": "led_to", "weight": 0.85},
                          {"target": "حقوق الإنسان", "type": "established", "weight": 0.9}],
        },
        {
            "concept": "الإمبراطورية الرومانية",
            "text": "من 27 ق.م حتى 476 م. أكبر وأطول إمبراطوريات التاريخ الغربي. وضعت أسس القانون واللغات اللاتينية والهندسة.",
            "cluster": "تاريخ قديم", "importance": 0.96, "certainty": 0.95, "abstraction": 0.4,
            "year": -27,
            "relations": [{"target": "القانون الروماني", "type": "created", "weight": 0.9},
                          {"target": "الحضارة اليونانية", "type": "inherited_from", "weight": 0.85}],
        },
        {
            "concept": "الفتح الإسلامي",
            "text": "انتشار الإسلام من شبه الجزيرة العربية في القرن السابع الميلادي. في أقل من قرن، امتد الفتح من إسبانيا إلى الهند.",
            "cluster": "تاريخ إسلامي", "importance": 0.96, "certainty": 0.95, "abstraction": 0.4,
            "year": 632,
            "relations": [{"target": "الخلافة الإسلامية", "type": "established", "weight": 0.9},
                          {"target": "العصر الذهبي الإسلامي", "type": "led_to", "weight": 0.85}],
        },
        {
            "concept": "العصر الذهبي الإسلامي",
            "text": "750-1258 م. ازدهار العلوم والفلسفة والطب والرياضيات. علماء كابن سينا والخوارزمي والبيروني.",
            "cluster": "تاريخ إسلامي", "importance": 0.95, "certainty": 0.93, "abstraction": 0.5,
            "year": 750,
            "relations": [{"target": "ابن سينا", "type": "produced", "weight": 0.9},
                          {"target": "الخوارزمي", "type": "produced", "weight": 0.9}],
        },
        {
            "concept": "الثورة الأمريكية",
            "text": "1775-1783. استقلال الولايات المتحدة عن بريطانيا. وثيقة الاستقلال 1776 أعلنت مبادئ المساواة والحرية.",
            "cluster": "تاريخ حديث", "importance": 0.93, "certainty": 0.97, "abstraction": 0.35,
            "year": 1775,
            "relations": [{"target": "الثورة الفرنسية", "type": "inspired", "weight": 0.8}],
        },
        {
            "concept": "الحرب الباردة",
            "text": "1947-1991. توتر بين الولايات المتحدة والاتحاد السوفيتي. سباق تسلح وفضاء وصراعات بالوكالة. انتهت بانهيار الاتحاد السوفيتي.",
            "cluster": "تاريخ معاصر", "importance": 0.95, "certainty": 0.97, "abstraction": 0.4,
            "year": 1947,
            "relations": [{"target": "الحرب العالمية الثانية", "type": "follows", "weight": 0.85},
                          {"target": "سباق الفضاء", "type": "includes", "weight": 0.85}],
        },
        {
            "concept": "الثورة الرقمية",
            "text": "من 1970 حتى اليوم. تحول من الاقتصاد الصناعي إلى اقتصاد المعلومات. الحاسوب والإنترنت غيّرا كل جانب من حياة الإنسان.",
            "cluster": "تاريخ معاصر", "importance": 0.96, "certainty": 0.95, "abstraction": 0.5,
            "year": 1970,
            "relations": [{"target": "الذكاء الاصطناعي", "type": "enables", "weight": 0.85}],
        },
        {
            "concept": "حضارة بلاد الرافدين",
            "text": "أقدم حضارة معروفة. نشأت بين نهري دجلة والفرات. اخترعت الكتابة المسمارية والقوانين (حمورابي) والزراعة المنظمة.",
            "cluster": "تاريخ قديم", "importance": 0.95, "certainty": 0.92, "abstraction": 0.4,
            "year": -3500,
            "relations": [{"target": "الكتابة", "type": "invented", "weight": 0.9},
                          {"target": "الزراعة", "type": "developed", "weight": 0.85}],
        },
        {
            "concept": "الحضارة المصرية القديمة",
            "text": "استمرت 3000 سنة. بنت الأهرامات ونظّمت الكتابة الهيروغليفية. حضارة نيل ألهمت كل حضارات المتوسط.",
            "cluster": "تاريخ قديم", "importance": 0.95, "certainty": 0.93, "abstraction": 0.4,
            "year": -3100,
            "relations": [{"target": "الأهرامات", "type": "built", "weight": 0.9}],
        },
    ]


def get_biology_items() -> List[Dict[str, Any]]:
    return [
        {
            "concept": "نظرية التطور",
            "text": "داروين 1859: الكائنات الحية تتطور عبر الانتخاب الطبيعي. الأفراد الأصلح للبيئة يبقون ويتكاثرون.",
            "cluster": "تطور", "importance": 0.99, "certainty": 0.97, "abstraction": 0.6,
            "year": 1859,
            "relations": [{"target": "الجينات", "type": "explained_by", "weight": 0.9},
                          {"target": "الانتخاب الطبيعي", "type": "includes", "weight": 0.95}],
        },
        {
            "concept": "الخلية",
            "text": "الوحدة الأساسية للحياة. كل كائن حي يتكون من خلية واحدة أو أكثر. تحتوي على غشاء وسيتوبلازم ومادة وراثية.",
            "cluster": "بيولوجيا خلوية", "importance": 0.98, "certainty": 1.0, "abstraction": 0.4,
            "year": 1665,
            "relations": [{"target": "الميتوكوندريا", "type": "contains", "weight": 0.85},
                          {"target": "الحمض النووي", "type": "contains", "weight": 0.95}],
        },
        {
            "concept": "الحمض النووي DNA",
            "text": "جزيء ثنائي اللولب يحمل المعلومات الوراثية. يتكون من أربعة قواعد: A, T, C, G. يشفّر بناء البروتينات.",
            "cluster": "وراثة", "importance": 0.99, "certainty": 1.0, "abstraction": 0.5,
            "year": 1953,
            "relations": [{"target": "الجينات", "type": "contains", "weight": 0.95},
                          {"target": "البروتينات", "type": "encodes", "weight": 0.9},
                          {"target": "الخلية", "type": "part_of", "weight": 0.9}],
        },
        {
            "concept": "الجينات",
            "text": "وحدات الوراثة. مقاطع من DNA تشفّر بروتينات أو RNA وظيفية. الإنسان لديه ~20,000-25,000 جين.",
            "cluster": "وراثة", "importance": 0.97, "certainty": 0.98, "abstraction": 0.5,
            "year": 1865,
            "relations": [{"target": "الحمض النووي DNA", "type": "part_of", "weight": 0.95},
                          {"target": "التطور", "type": "mechanism_of", "weight": 0.9}],
        },
        {
            "concept": "البروتينات",
            "text": "جزيئات ضخمة تؤدي معظم وظائف الخلية. مبنية من الأحماض الأمينية. الإنزيمات والأجسام المضادة والهرمونات كلها بروتينات.",
            "cluster": "كيمياء حيوية", "importance": 0.96, "certainty": 1.0, "abstraction": 0.5,
            "year": 1838,
            "relations": [{"target": "الحمض النووي DNA", "type": "encoded_by", "weight": 0.95},
                          {"target": "الإنزيمات", "type": "type_of", "weight": 0.9}],
        },
        {
            "concept": "التمثيل الضوئي",
            "text": "عملية تحويل الضوء وثاني أكسيد الكربون والماء إلى جلوكوز وأكسجين في النباتات والطحالب. 6CO₂ + 6H₂O + ضوء → C₆H₁₂O₆ + 6O₂.",
            "cluster": "فيزيولوجيا نباتية", "importance": 0.97, "certainty": 1.0, "abstraction": 0.4,
            "year": 1779,
            "relations": [{"target": "الكلوروفيل", "type": "uses", "weight": 0.9},
                          {"target": "الأكسجين", "type": "produces", "weight": 0.95}],
        },
        {
            "concept": "المنظومة المناعية",
            "text": "شبكة من الخلايا والأعضاء تحمي الجسم من المرض. تشمل: الكريات البيضاء، الأجسام المضادة، الغدة الصعترية.",
            "cluster": "فيزيولوجيا", "importance": 0.93, "certainty": 0.97, "abstraction": 0.5,
            "year": 1880,
            "relations": [{"target": "الأجسام المضادة", "type": "produces", "weight": 0.9},
                          {"target": "اللقاحات", "type": "trained_by", "weight": 0.85}],
        },
        {
            "concept": "الشبكة الغذائية",
            "text": "علاقات الأكل والأكل في النظام البيئي. المنتجون (نباتات) → المستهلكون الأوليون → الثانويون → المحللون.",
            "cluster": "بيئة", "importance": 0.90, "certainty": 0.97, "abstraction": 0.5,
            "year": 1927,
            "relations": [{"target": "النظام البيئي", "type": "part_of", "weight": 0.9},
                          {"target": "التمثيل الضوئي", "type": "begins_with", "weight": 0.85}],
        },
        {
            "concept": "التصنيف البيولوجي",
            "text": "نظام لينيوس لتصنيف الكائنات: مملكة → شعبة → رتبة → فصيلة → جنس → نوع.",
            "cluster": "تصنيف", "importance": 0.90, "certainty": 1.0, "abstraction": 0.5,
            "year": 1735,
            "relations": [{"target": "نظرية التطور", "type": "reorganized_by", "weight": 0.85}],
        },
        {
            "concept": "علم الأعصاب",
            "text": "دراسة الجهاز العصبي. الدماغ يحتوي ~86 مليار خلية عصبية. تتواصل عبر نبضات كهربائية وناقلات كيميائية.",
            "cluster": "علم أعصاب", "importance": 0.95, "certainty": 0.92, "abstraction": 0.6,
            "year": 1870,
            "relations": [{"target": "الخلية العصبية", "type": "studies", "weight": 0.95},
                          {"target": "الذكاء الاصطناعي", "type": "inspired", "weight": 0.85}],
        },
        {
            "concept": "الميكروبيوم البشري",
            "text": "تريليونات الميكروبات التي تعيش في ومع الإنسان. تؤثر على الهضم والمناعة والصحة النفسية.",
            "cluster": "ميكروبيولوجيا", "importance": 0.88, "certainty": 0.88, "abstraction": 0.5,
            "year": 2003,
            "relations": [{"target": "المنظومة المناعية", "type": "interacts_with", "weight": 0.85}],
        },
        {
            "concept": "CRISPR",
            "text": "تقنية تحرير الجينات الثورية. تسمح بقطع ولصق أجزاء من DNA بدقة عالية. فتحت آفاقاً لعلاج الأمراض الوراثية.",
            "cluster": "هندسة وراثية", "importance": 0.93, "certainty": 0.92, "abstraction": 0.6,
            "year": 2012,
            "relations": [{"target": "الجينات", "type": "edits", "weight": 0.95},
                          {"target": "الحمض النووي DNA", "type": "modifies", "weight": 0.9}],
        },
    ]


def get_civilizations_items() -> List[Dict[str, Any]]:
    return [
        {
            "concept": "الحضارة الإغريقية",
            "text": "أسست الفلسفة والديمقراطية والرياضيات والمسرح. أفلاطون وأرسطو وإقليدس وأرخميدس. أثّرت في كل الحضارة الغربية.",
            "cluster": "حضارات قديمة", "importance": 0.97, "certainty": 0.95, "abstraction": 0.5,
            "year": -800,
            "relations": [{"target": "الفلسفة", "type": "founded", "weight": 0.95},
                          {"target": "الديمقراطية", "type": "invented", "weight": 0.9},
                          {"target": "الإمبراطورية الرومانية", "type": "influenced", "weight": 0.9}],
        },
        {
            "concept": "الحضارة الصينية",
            "text": "من أقدم الحضارات المستمرة. اخترعت الورق والبارود والمطبعة والبوصلة. الجدار العظيم والحرير والخزف.",
            "cluster": "حضارات آسيا", "importance": 0.96, "certainty": 0.93, "abstraction": 0.5,
            "year": -2000,
            "relations": [{"target": "طريق الحرير", "type": "created", "weight": 0.85},
                          {"target": "اختراع الورق", "type": "achieved", "weight": 0.95}],
        },
        {
            "concept": "الحضارة الإسلامية",
            "text": "جمعت معارف اليونان والفرس والهند وطوّرتها. أسهمت في الطب والجبر والفلك والفلسفة وصون التراث الإنساني.",
            "cluster": "حضارات إسلامية", "importance": 0.96, "certainty": 0.93, "abstraction": 0.5,
            "year": 622,
            "relations": [{"target": "العصر الذهبي الإسلامي", "type": "produced", "weight": 0.95},
                          {"target": "الجبر", "type": "invented", "weight": 0.9}],
        },
        {
            "concept": "عصر النهضة الأوروبية",
            "text": "القرنان 14-17. إحياء الفنون والعلوم. ليوناردو دا فينشي ومايكلانجيلو وغاليليو. بداية العلم الحديث.",
            "cluster": "حضارات أوروبية", "importance": 0.95, "certainty": 0.95, "abstraction": 0.5,
            "year": 1350,
            "relations": [{"target": "الثورة العلمية", "type": "led_to", "weight": 0.9},
                          {"target": "الفن الأوروبي", "type": "transformed", "weight": 0.85}],
        },
        {
            "concept": "حضارة الهنود الأمريكيين",
            "text": "الأزتيك والمايا والإنكا. المايا اخترعوا التقويم والأرقام والكتابة. الأزتيك بنوا تينوتشتيتلان. الإنكا بنوا ماتشو بيتشو.",
            "cluster": "حضارات أمريكا", "importance": 0.90, "certainty": 0.90, "abstraction": 0.5,
            "year": -500,
            "relations": [{"target": "الزراعة", "type": "advanced", "weight": 0.85}],
        },
        {
            "concept": "طريق الحرير",
            "text": "شبكة تجارية ربطت الصين بأوروبا والعالم الإسلامي. نقلت البضائع والأفكار والأمراض والدين عبر آسيا لقرون.",
            "cluster": "تبادل حضاري", "importance": 0.90, "certainty": 0.92, "abstraction": 0.4,
            "year": -130,
            "relations": [{"target": "الحضارة الصينية", "type": "created_by", "weight": 0.85},
                          {"target": "العولمة", "type": "precursor_to", "weight": 0.75}],
        },
        {
            "concept": "الثورة العلمية",
            "text": "القرن 16-17. غاليليو وكوبرنيكوس وكبلر ونيوتن. الطريقة التجريبية حلّت محل السلطة الدينية في فهم الطبيعة.",
            "cluster": "تاريخ العلوم", "importance": 0.96, "certainty": 0.95, "abstraction": 0.55,
            "year": 1543,
            "relations": [{"target": "عصر النهضة الأوروبية", "type": "follows", "weight": 0.85},
                          {"target": "الثورة الصناعية", "type": "enabled", "weight": 0.85}],
        },
        {
            "concept": "الكتابة",
            "text": "أحد أعظم اختراعات الإنسانية. بدأت بالكتابة المسمارية السومرية ~3200 ق.م ثم الهيروغليفية. مكّنت نقل المعرفة عبر الزمن.",
            "cluster": "إنجازات إنسانية", "importance": 0.99, "certainty": 0.95, "abstraction": 0.4,
            "year": -3200,
            "relations": [{"target": "حضارة بلاد الرافدين", "type": "invented_by", "weight": 0.9},
                          {"target": "العلوم", "type": "enabled", "weight": 0.95}],
        },
        {
            "concept": "الفلسفة",
            "text": "البحث في الأسئلة الأساسية: الوجود، المعرفة، الأخلاق، العقل. سقراط وأفلاطون وأرسطو أسسوا المنهج الغربي.",
            "cluster": "فكر إنساني", "importance": 0.95, "certainty": 0.85, "abstraction": 0.9,
            "year": -600,
            "relations": [{"target": "الحضارة الإغريقية", "type": "originated_in", "weight": 0.9},
                          {"target": "العلوم", "type": "parent_of", "weight": 0.85}],
        },
        {
            "concept": "العولمة",
            "text": "تزايد الترابط الاقتصادي والثقافي والسياسي بين شعوب العالم. الإنترنت والتجارة الدولية والهجرة محركاتها الرئيسية.",
            "cluster": "حضارة معاصرة", "importance": 0.92, "certainty": 0.90, "abstraction": 0.6,
            "year": 1990,
            "relations": [{"target": "الثورة الرقمية", "type": "accelerated_by", "weight": 0.9}],
        },
    ]


def get_all_domain_items() -> Dict[str, List[Dict[str, Any]]]:
    """يُرجع جميع مصادر المجالات دفعة واحدة."""
    return {
        "physics":       get_physics_items(),
        "math":          get_math_items(),
        "history":       get_history_items(),
        "biology":       get_biology_items(),
        "civilizations": get_civilizations_items(),
    }
